import { z } from 'zod/v4'

/**
 * Schema for a single recipe generated by the AI.
 * Nutrition is REQUIRED (not optional) for AI-generated recipes.
 */
export const aiRecipeSchema = z.object({
  title: z.string().min(1).max(200),
  description: z.string().max(2000).nullable().optional(),
  prepTimeMinutes: z.number().int().min(0).max(1440),
  cookTimeMinutes: z.number().int().min(0).max(1440),
  baseServings: z.number().int().min(1).max(100),
  difficulty: z.enum(['EASY', 'MEDIUM', 'HARD']),
  cuisineType: z.string().max(50).nullable().optional(),
  ingredients: z.array(z.object({
    quantity: z.number().positive().nullable().optional(),
    unit: z.string().max(30).nullable().optional(),
    name: z.string().min(1).max(200),
    notes: z.string().max(500).nullable().optional(),
    orderIndex: z.number().int().min(0),
  })).min(1),
  instructions: z.array(z.object({
    stepNumber: z.number().int().min(1),
    instructionText: z.string().min(1).max(2000),
    durationMinutes: z.number().int().min(1).max(480).nullable().optional(),
  })).min(1),
  tags: z.array(z.object({ tagName: z.string().min(1).max(50) })).optional().default([]),
  nutrition: z.object({
    caloriesPerServing: z.number().int().min(0),
    proteinG: z.number().min(0),
    carbsG: z.number().min(0),
    fatG: z.number().min(0),
  }),
})

export const aiMealSchema = z.object({
  dayIndex: z.number().int().min(0).max(6),
  mealType: z.enum(['BREAKFAST', 'LUNCH', 'DINNER', 'SNACK']),
  recipe: aiRecipeSchema,
})

export const aiMealPlanOutputSchema = z.object({
  meals: z.array(aiMealSchema).min(28).max(28),
})

/** Schema for a single swapped meal */
export const aiSingleMealOutputSchema = z.object({
  recipe: aiRecipeSchema,
})

export type AiMealPlanOutput = z.infer<typeof aiMealPlanOutputSchema>
export type AiRecipeOutput = z.infer<typeof aiRecipeSchema>
export type AiMealOutput = z.infer<typeof aiMealSchema>
export type AiSingleMealOutput = z.infer<typeof aiSingleMealOutputSchema>
